version: '2'
services:
#  db:
#    image: postgres
#    volumes:
#        - ./data:/var/lib/postgresql/data
#    env_file: .env

#  os-viewer:
#    build:
#      context: ./osviewer
#    environment:
#      - "OS_VIEWER_BASE_PATH="
#    volumes:
#      - ./os_viewer_themes:/app/app/config/themes
#    ports:
#      - "4000:4000"

  microsite:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#      - os-viewer
    environment:
      # non secret static environment variables
      - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
      - OS_VIEWER_HOST=http://next.openspending.org/viewer
      - OS_API=http://next.openspending.org/api/3
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      # uncomment or supply the following via command line to use the postgres db
      # - DJANGO_SETTINGS_MODULE=microsite_backend.production_settings
    # secrets are defined externally in .env
    env_file: .env
    # .env needs to define:
    #   SECRET_KEY="mykey"
    #   POSTGRES_DB=postgres
    #   POSTGRES_USER=postgres
    #   POSTGRES_PASSWORD=postgres


volumes:
  data:
